---
- name: Get running config for backups
  hosts: CVP-SERVER
  connection: local
  gather_facts: false
  collections:
    - arista.cvp
  tasks:
    - name: '#02 - Collect devices facts from {{inventory_hostname}}'
      arista.cvp.cv_facts_v3:
        facts:
          - configlets
        regexp_filter: "AVD_DC1-LEAF1A"
      register: FACTS_DEVICES

    - name: Print stuff
      debug:
        var: FACTS_DEVICES.data.cvp_configlets

    - name: save somewhere
      local_action:
        module: copy
        content: "{{ FACTS_DEVICES.data.cvp_configlets['AVD_DC1-LEAF1A']}}"
        dest: "/tmp/muhtest.cfg"