---
port_profiles:
  TENANT_A:
    mode: access
    vlans: "110"


servers:
  Server01:
    rack: POD1
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet3]
        switches: [DC1-L2LEAF1A]
        profile: TENANT_A

  host2:
    rack: POD2
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet3]
        switches: [DC1-L2LEAF2A]
        profile: TENANT_A
