---
- name: Service now ticket creation
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm
  tasks:
  - name: Create incident
    servicenow.itsmincident:
      instance:
        host: https://dev119598.service-now.com
        username: admin
        password: "{{ lookup('ansible.builtin.env', 'SNOW_PASS') }}"

      state: new
      caller: ansible.eda
      short_description: Check device status
      description: Device is currently in maintenance mode
      # attachments:
      #   - path: ./config/test.txt
      impact: low
      urgency: low