---
- name: Listen for events on nats
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: check down interface
      condition:
        all:
          - event.payload.receiver == "EDAwebhook"
          - event.payload.status == "firing"

  ## Create an action once the data has hit the condition.
      action:
        run_playbook:
          name: test.yaml