---
- name: Listen for events from cloudvision webhooks
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Get webhook data store as a fact.
      condition:
        all:
          ### This needs to key a bit further for sure other than this generic regex of the string search.
          - event.payload is search("Device In Maintenance Mode", ignorecase=true)
  ## Create an action once the data has hit the condition.
      action:
        run_playbook:
          name: test.yaml
