---
- name: CVPWebhookAlerter
  hosts: all
  sources:
    - name: cvp
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
        skip_original_data: true
      filters:
       - ansible.eda.json_filter:
           exclude_keys:
             - receiver
             - commonLabels
             - groupLabels
             - commonAnnotations
             - externalURL
             - groupKey
             - truncatedAlerts
             - version
  rules:
    - name: Condition for firing into Maintenance mode.
      condition:
        all:
          - event.alert.status == "firing" and event.alert.labels.eventType == "DEVICE_MAINTENANCE_MODE"
      action:
        run_playbook:
          name: set.yaml
    - name: Condition for resolving into Maintenance mode.
      condition:
        all:
          - event.alert.status == "resolved" and event.alert.labels.eventType == "DEVICE_MAINTENANCE_MODE"
      action:
        run_playbook:
          name: unset.yaml