---
- name: Listen for events from cloudvision webhooks
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Get webhook data store as a fact.
      condition:
        all:
          - event.payload.receiver == "EDAwebhook" and event.payload.alerts is selectattr('status', 'search', "firing") and event.payload.alerts is selectattr('labels.eventType', 'search', "DEVICE_MAINTENANCE_MODE")
      action:
        run_playbook:
          name: set.yaml
    - name: Once MM is unset
      condition:
        all:
        - event.payload.receiver == "EDAwebhook" and event.payload.alerts is selectattr('status', 'search', "resolved") and event.payload.alerts is selectattr('labels.eventType', 'search', "DEVICE_MAINTENANCE_MODE")
      action:
        run_playbook:
          name: unset.yaml